discordid = '407157653475819530'; //Здесь должен быть ID пользователя дискорд (обязательно)
user_firstname = 'SmookyWizard'; //Имя пользователя или псевдоним (Обязательно)
userbio = 'Лев — это твоя жадная душа, а лиса — это дьявол, вводящий тебя в заблуждение.'; //Описание профиля пользователя (обязательно)

github_login = 'Rxflex'; // Ник на платформе GitHub (Обязательно)
instagram_login = '@smookywizard'; //Логин от инстаграм (Не обязательно)
website_url = 'smookywizard.ru'; // Ссылка на сайт (Не обязательно)
twitter_login = ''; // Логин от твиттер (Не обязательно)

profile_theme = 'dark'; // Стиль профиля, доступные стили dark, light
profile_color = 'rgb(32, 34, 37)'; // Цвет рамки профиля
